site_name: Project 2A
site_author: Mirantis
docs_dir: ./docs
repo_name: GitHub
repo_url: https://github.com/mirantis/hmc
copyright:
  '© 2005 - 2024 Mirantis, Inc. All rights reserved.'
theme:
  name: "material"
  font:
    text: Overpass
    code: Roboto Mono
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  
  icon: assets/mirantis-logo-inverted-horizontal-one-color.svg
  logo: assets/mirantis-logo-inverted-horizontal-one-color.svg
  favicon: assets/favicon.ico

  search: true
  search_index_only: true
  features:
    - toc.autohide
    - toc.integrate
    - search.suggest
    - search.highlight
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.path
    - content.code.copy

extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - mermaid2

#extra:
#  generator: false

# Page tree

markdown_extensions:
  - callouts
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Installation:
      - Quick Start: install/quick-start.md
      - Installation Guide: install/installation.md
      - Templates: template/main.md
      - Credential System: credential/main.md
  - Developer Guide: dev.md
  - Provider Guides:
    - AWS: 
      - aws/main.md
      - aws/cloudformation.md
      - aws/cluster-parameters.md
      - aws/hosted-control-plane.md
      - aws/nuke.md
    - Azure: 
      - azure/main.md
      - azure/cluster-parameters.md
      - azure/hosted-control-plane.md
      - azure/machine-parameters.md
    - Vsphere: 
      - vsphere/main.md
      - vsphere/cluster-parameters.md
      - vsphere/hosted-control-plane.md
      - vsphere/machine-parameters.md
