name: Publish docs
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure all history and tags are fetched

      - name: Configure Git Credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Restore Cached Dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache/pip
          restore-keys: |
            mkdocs-material-
        
      - name: Generate Cache Key (if cache is missing)
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: |
            echo "cache_id=mkdocs-material-$(date --utc '+%V')" >> $GITHUB_ENV
            mkdir ~/.cache/pip
        
      - name: Install mkdocs-material and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --disable-pip-version-check -r requirements.txt

      - name: Check and initialize gh-pages if missing
        id: check_branch
        run: |
          if git ls-remote --heads origin gh-pages | grep -q gh-pages; then
            echo "✅ gh-pages branch already exists. Proceeding with deployment..."
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "🚀 gh-pages branch is missing. Will initialize using init_docs.yml..."
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        
      - name: Init docs as gh-pages is missing
        if: steps.check_branch.outputs.exists == 'false'
        run: mkdocs gh-deploy

      - name: Deploy to main branch (head)
        run: mike deploy head --push
